Day 1
Oscar-Espinoza/CC-Global-Summit pull request #1
Opened 2022-11-22 22:39 UTC by Oscar-Espinoza

Home and about views are created with most of the styling, and the comedian's list on the home page is created dynamically with js, nothing else is dynamic yet, the footer and the readme documentation is not done yet

2022-11-23 23:54 UTC, Munsa1 requested changes
Hi @Oscar-Espinoza, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

Great video presentation, it was professional, clear and straight to the point


## Suggested changes
_Check the comments under the review._
- [x] The Project has not been deployed using GIthub Pages, kindly do so and provide the link in the readme file.
![image](https://user-images.githubusercontent.com/81932478/203662940-6d06cf39-113a-4c17-a7f9-a62c869a22d4.png)

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-23 23:54 UTC, Munsa1 commented on index.html
> +        </ul>
- [ ] Kindly implement the Orange button to the left as it is in the given design, also implement the pressed button effect. If you look closeley you will see that the page on which the user is has a highlighted color to its corresponding link in the navigation.
#### Note that this applies fr the about page as well

Your design
![image](https://user-images.githubusercontent.com/81932478/203663427-aece643d-94d5-444b-ad6c-8270777fb6ba.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/203663453-5c9dfdc2-1b58-4aa1-be68-1c6a7f118ff9.png)

2022-11-23 23:54 UTC, Munsa1 commented on index.html
> +    <section class="about">
- [ ] The requirement is that you have to create two seperate html files, the index.html and the about.html respectively, kindly do so.

2022-11-23 23:54 UTC, Munsa1 commented on README.md
> +Loom video link:
- [ ] Kindly use the new Microverse template for the readme file as this is the latest requirement. [Follow this link](https://github.com/microverseinc/readme-template/blob/master/README.md)

2022-11-23 23:54 UTC, Munsa1 commented on index.html
> +    </section>
- [ ] This section has a subtitle at the top followed by the man title in the original design. kindly implement it in your design as well as this is a requirement.

Your design
![image](https://user-images.githubusercontent.com/81932478/203663831-472d589a-fea4-4199-8ae5-1885365d4861.png)

Given design
![image](https://user-images.githubusercontent.com/81932478/203664130-ab31758f-63ba-4002-9d47-051cb38c3dc4.png)

2022-11-23 23:54 UTC, Munsa1 commented on index.html
> +  </div>
- [ ] The partners and footer section have not been implemented in the index.html file and this includes the mobile view, kindy add them according to the given design.
![image](https://user-images.githubusercontent.com/81932478/203664864-aed6a178-be5e-4953-aaf2-95f1774f086d.png)

#### This applies for the about page as well

2022-11-24 20:23 UTC, aimalamiri requested changes
Hi @Oscar-Espinoza, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191356050-93e2eb80-7c05-4749-92f7-8925a1fa9386.gif)


 ## Highlights

- The pages are designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

 ## Required Changes ♻️

You did a great job, but you still have some points that can be improved which are mentioned in the bellow comments, but in here I'd like to mention that your project is not deployed properly. Because when I visited the deployment link I was able to see the Readme file not your web page. The possible reason for this in my opinion is that you renamed the `index.html` file to `home.html` page. Please make it `index.html` again so the GitHub can show the proper page.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 20:23 UTC, aimalamiri commented on home.html
> +    </section>
It looks great, but it's highly recommended to follow the original design idea as much as possible. Especially the colors, typography, and sizing. As you can see in the header the text size is much smaller than the original one, and the color is also not similar to the one in the original design **(Idea: Using the CSS [gradients](https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient) can be helpful)**. Please make sure to increase the text size and use a similar color.


Yours
![image](https://user-images.githubusercontent.com/34779928/203856563-f3a2fd05-d850-42d8-8d16-3dce19b52b10.png)

Original
![image](https://user-images.githubusercontent.com/34779928/203856678-a742e561-165c-49ea-9926-550f6cea622d.png)

2022-11-24 20:23 UTC, aimalamiri commented on home.html
> +
The design is implemented very well, but you can improve it by increasing its font size here.

Yours
![image](https://user-images.githubusercontent.com/34779928/203857206-0961f8b1-f4f7-47d5-90a3-bcfeab5c63d6.png)

Original
![image](https://user-images.githubusercontent.com/34779928/203857230-d2614c6e-fa65-49c4-92be-e0fe11c7bd8e.png)

2022-11-24 20:23 UTC, aimalamiri commented on home.html
> +        </li>
Adding a hover effect will make it somewhat interactive. As you can see in the original design you can implement the hover effect by adding a white bold border to these cards. Please make sure to implement this.

![image](https://user-images.githubusercontent.com/34779928/203857426-23705d03-b5ff-4739-bcd7-68f99e114ffd.png)

2022-11-24 20:23 UTC, aimalamiri commented on app.js
> +      `;
I like the way you implemented the javascript for generating the speakers. But it seems you can improve the design by following the original design idea. So for this please make sure to add the background picture for the speaker image, and also increase its size a little bit to make it look much more similar to the one in the original design..

![image](https://user-images.githubusercontent.com/34779928/203857787-c56558b3-197e-4e48-b192-184e6b5fb880.png)

2022-11-24 20:23 UTC, aimalamiri commented on about.html
> +  </section>
You're almost there, but you still have some opportunities to improve by following the sizing from the original design idea. 

Here I'd highly recommend increasing the text size.

Yours
![image](https://user-images.githubusercontent.com/34779928/203858316-f525e987-7196-45cb-9f5a-ec77871a01fb.png)

Original
![image](https://user-images.githubusercontent.com/34779928/203858351-abdf7615-6cd9-493c-8d09-074f6d2903cd.png)

2022-11-24 20:23 UTC, aimalamiri commented on README.md
> +- [Live Demo Link](https://www.loom.com/share/4685dac778c7469fb5d9b3a97d199be6)
The live demo link must be the link to your deployed web page, not to your presentation video. Kindly make sure to update this.

2022-11-24 20:23 UTC, aimalamiri commented on README.md
> +I would like to thank Microverse for encourage me to do this project.
It's required to mention the original design idea owner. In our case, it's [Cindy](https://www.behance.net/adagio07). Please make sure to update your readme file with proper credits.

2022-11-25 17:23 UTC, jerryowusu approved these changes
Hi @Oscar-Espinoza , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![clap approve](https://user-images.githubusercontent.com/65233860/204032654-09d69b8c-64be-4dc2-89f7-a0cb5a38e75e.gif)


## Highlights
Neat and clean code :heavy_check_mark: 
All linters are passing :heavy_check_mark: 
Followed GitHub flow :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 17:23 UTC, jerryowusu commented on README.md
> +- [Live Demo Link](https://oscar-espinoza.github.io/CC-Global-Summit/)
[OPTIONAL] Well done for successfully deploying the project on github. :+1:  However, you need to ensure that everything works fine as it's suppose to be. Currently the images under the main program section are not displaying, kindly check and fix it. :pray:

2022-11-25 17:50 UTC, merged